In [ ]:
!pip install anchor-exp


Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 427.3/427.3 kB 9.3 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 275.7/275.7 kB 27.1 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
  Created wheel for anchor-exp: filename=anchor_exp-0.0.2.0-py3-none-any.whl size=433519 sha256=ffddee50af5aca7f481006f985eb1c492a6560a415b68cf5d192a8cd21cfd676
  Stored in directory: /root/.cache/pip/wheels/e9/53/45/7e4602020c5e5069ccef79f1389adb8efc4ca3c4d9891388bb
  Created wheel for lime: filename=lime-0.2.0.1-py3-none-any.whl size=283859 sha256=92e8203e7651d3d0a26b93e7976de48d21c37ef1970fcf0d4dbc7ec3549ebfeb
  Stored in directory: /root/.cache/pip/wheels/fd/a2/af/9ac0a1a85a27f314a06b39e1f492bee1547d52549a4606ed89
Successfully built anchor-exp lime


In [ ]:
import numpy as np
from sklearn.ensemble import RandomForestClassifier
from anchor import utils
from anchor import anchor_tabular
import pandas as pd

In [ ]:
# Load your data into a numpy array
train_data = pd.read_csv("FICO.full.csv")
train_data=pd.DataFrame(train_data)
train_data.to_csv("my_data.csv")
#data = pd.read_csv("my_data.csv")
data = np.genfromtxt("my_data.csv", delimiter=",")
data = data[1:]
data = data[:,1:]





In [ ]:
# Split your data into training and testing sets
X_train, y_train = data[:, :-1], data[:, -1]

# Train a random forest model on your training data
rf = RandomForestClassifier(n_estimators=100, max_depth=5)
rf.fit(X_train, y_train)
X_train.shape

(10459, 17)

In [ ]:
# Define a function that takes an instance and returns its predicted class label
predict_fn = lambda x: rf.predict(x.reshape(1, -1)).ravel()

# Define a function that checks if a given instance has a different class label than the original instance
def has_different_label(x, original_label):
    return rf.predict(x.reshape(1, -1)).ravel() != original_label

# Define a function that searches for a counterfactual instance using the Anchors algorithm
def search_counterfactual(x, original_label):
    # Define the search parameters
    search_params = {
        "sample_whole_training": False,
        "seed": 1
    }

    # Define the feature names and the class names
    feature_names = ["ExternalRiskEstimate<0.49","ExternalRiskEstimate<0.65","ExternalRiskEstimate<0.80","NumSatisfactoryTrades<0.5","TradeOpenTime<0.6","TradeOpenTime<0.85","TradeFrequency<0.45","TradeFrequency<0.6","Delinquency<0.55","Delinquency<0.75","Installment<0.5","Installment<0.7","Inquiry<0.75","RevolvingBalance<0.4","RevolvingBalance<0.6","Utilization<0.6","TradeWBalance<0.33"]
    class_names = ["0", "1"]

    # Create an Anchors explainer object for your random forest model
    explainer = anchor_tabular.AnchorTabularExplainer( class_names,feature_names,
        X_train
        
    )

    # Generate a counterfactual explanation for the given instance using Anchors
    explanation = explainer.explain_instance(
        x, rf.predict, threshold=0.95
    )

    # Search for a counterfactual instance that has a different class label
    
    cfe = explanation.examples(only_different_prediction=True)
    cfe_set = []
    for elt in cfe :
      if has_different_label(elt, original_label):
        cfe_set.append(elt)

    return cfe



In [ ]:
# Define an example instance and its original class label
instance = X_train[0]
original_label = rf.predict(instance.reshape(1, -1)).ravel()[0]
instance



array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 1., 0., 0., 1., 1., 0.])

In [ ]:
# Search for a counterfactual instance that has a different class label
counterfactual_set = search_counterfactual(instance, original_label)

#if counterfactual_set:
    #print("Counterfactual instance found:", counterfactual_set)
#else:
    #print("Counterfactual instance not found.")

In [ ]:
counterfactual_set

array([[0., 0., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 0., 1., 1., 1.,
        1.],
       [0., 0., 1., 1., 0., 1., 0., 0., 1., 1., 1., 1., 1., 1., 1., 1.,
        0.],
       [0., 0., 1., 1., 1., 1., 0., 1., 0., 1., 1., 1., 1., 1., 1., 1.,
        1.],
       [0., 0., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1.,
        1.],
       [0., 0., 1., 1., 0., 1., 0., 0., 0., 1., 1., 1., 1., 1., 1., 1.,
        1.],
       [0., 0., 1., 1., 0., 1., 0., 1., 0., 1., 1., 1., 1., 1., 1., 1.,
        1.],
       [0., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1.,
        0.],
       [0., 0., 1., 1., 0., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1.,
        1.],
       [0., 0., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1.,
        1.],
       [0., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 1., 1.,
        1.]])

In [ ]:
# https://github.com/marcotcr/anchor/blob/b1f5e6ca37428613723597e85c38558e8cd21c2e/anchor/anchor_explanation.py#L5
# https://arxiv.org/pdf/1805.10820.pdf
# https://github.com/riccotti/LORE/blob/master/test_lore.py

In [ ]:
from prepare_dataset import collectTreesRF, exportTreeCollection

In [ ]:
n_nodesRF, children_leftRF, children_rightRF, featureRF, thresholdRF, node_depthRF, is_leavesRF, nodeValuesRF = collectTreesRF(rf)
exportTreeCollection("Ficofull", "RF",  0, len(X_train[0]), len(rf.classes_),
                             n_nodesRF, children_leftRF, children_rightRF, featureRF, thresholdRF,
                             node_depthRF, is_leavesRF, nodeValuesRF)

In [ ]:
def export_region(vectors,filename) :
    vectors = np.array(vectors)

    min_vectors=np.min(vectors,axis=0)
    max_vectors=np.max(vectors, axis=0)

    with open(filename, 'w') as f:
        np.savetxt(f, [min_vectors], fmt='%.2f', delimiter=',', newline='\n')
        np.savetxt(f, [max_vectors], fmt='%.2f', delimiter=',', newline='\n')


    return min_vectors, max_vectors

In [ ]:
our_set = list(counterfactual_set) 
our_set.append(instance)
our_set

[array([0., 0., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1.]),
 array([0., 0., 1., 1., 0., 1., 0., 0., 1., 1., 1., 1., 1., 1., 1., 1., 0.]),
 array([0., 0., 1., 1., 1., 1., 0., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1.]),
 array([0., 0., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1.]),
 array([0., 0., 1., 1., 0., 1., 0., 0., 0., 1., 1., 1., 1., 1., 1., 1., 1.]),
 array([0., 0., 1., 1., 0., 1., 0., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1.]),
 array([0., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 0.]),
 array([0., 0., 1., 1., 0., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1.]),
 array([0., 0., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1.]),
 array([0., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1.]),
 array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 1., 0., 0., 1., 1., 0.])]

In [ ]:
a,b = export_region(our_set,"region_cf_set.txt")

In [ ]:
a,b

(array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 1., 0., 0., 1., 1., 0.]),
 array([0., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]))